image: gitlab.hbm.com:5555/docker/next:latest

variables:
  LANG: en_US.UTF-8
  LC_MESSAGES: POSIX
  GIT_SUBMODULE_STRATEGY: recursive
  BB_ENV_EXTRAWHITE: "$BB_ENV_EXTRAWHITE SSTATE_DIR SSTATE_MIRRORS DL_DIR"
  SSTATE_DIR: /share/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/build-sstate-cache
  SSTATE_MIRRORS: " file://.* file:///share/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/build-sstate-cache/PATH "
  DL_DIR: /downloads/yocto
  DEPLOY_DIR:  "${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/${CI_BUILD_NAME}/${CI_COMMIT_REF_NAME}"

before_script:
  - sudo mkdir -p ${SSTATE_DIR}
  - sudo chown buildbot:buildbot ${SSTATE_DIR}
  - sudo mkdir -p /downloads/yocto
  - sudo chown buildbot:buildbot /downloads/yocto

stages:
  - clean
  - get
  - build

######
# GET
######

get-ngt:
  stage: get
  variables:
    MACHINE: ngt-board
    BB_ENV_EXTRAWHITE: "$BB_ENV_EXTRAWHITE DL_DIR"
    DL_DIR: /downloads/yocto
  script:
    - ./bootstrap-yocto
    - source setup-environment build-ngt
    - bitbake ubifs-image --runall=fetch
  tags:
    - docker

#get-atlas:
#  stage: get
#  variables:
#    MACHINE: atlas-board
#  script:
#    - env
#    - ./bootstrap-yocto
#    - source setup-environment build-atlas
#    - bitbake sd-image --runall=fetch
#  tags:
#    - docker

#######
# BUILD
#######

build-ngt:
  stage: build
  variables:
    MACHINE: ngt-board
    BB_ENV_EXTRAWHITE: "$BB_ENV_EXTRAWHITE DL_DIR"
    DL_DIR: /downloads/yocto
  script:
    - ./bootstrap-yocto
    - source setup-environment build-ngt
    - bitbake ubifs-image -c populate_sdk
    - bitbake ubifs-image
  after_script:
    - echo "Deploy to http://berta.devel.hbm.com/gitlab-runner/share/${DEPLOY_DIR}/${CI_BUILD_ID}/deploy"
    - echo "Deploy to http://localhost:8888/gitlab-runner/share/${DEPLOY_DIR}/${CI_BUILD_ID}/deploy "
    - sudo mkdir -p /share/${DEPLOY_DIR}/${CI_BUILD_ID}/deploy
    - sudo cp -rP build-ngt/tmp/deploy/* /share/${DEPLOY_DIR}/${CI_BUILD_ID}/deploy/
  tags:
    - docker

  tags:
    - docker



#build-atlas:
#  stage: build
#  variables:
#    MACHINE: atlas-board
#  script:
#    - env
#    - ./bootstrap-yocto
#    - source setup-environment build-atlas
#    - bitbake sd-image
#  tags:
#    - docker


#######
# SCHEDULED BUILDS
#######

### REMOVE STATE/IMAGE CACHES
clean:
  stage: clean
  only:
    - schedules
  script:
    - sudo rm -fr /share/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/build-*
    - sudo rm -fr /share/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/firmware-*
  tags:
    - docker

firmware-ngt:
  stage: build
  only:
    - schedules
  variables:
    MACHINE: ngt-board
    BB_ENV_EXTRAWHITE: "$BB_ENV_EXTRAWHITE DL_DIR"
    DL_DIR: /downloads/yocto
  script:
    - ./bootstrap-yocto
    - source setup-environment build-ngt
    - bitbake ubifs-image -c populate_sdk
    - bitbake ubifs-image
  after_script:
    - echo "Deploy to http://berta.devel.hbm.com/gitlab-runner/share/${DEPLOY_DIR}/deploy"
    - echo "Deploy to http://localhost:8888/gitlab-runner/share/${DEPLOY_DIR}/deploy "
    - sudo mkdir -p /share/${DEPLOY_DIR}/deploy
    - sudo cp -rP build-ngt/tmp/deploy/* /share/${DEPLOY_DIR}/deploy/
  tags:
    - docker

#firmware-atlas:
#  stage: build
#  only:
#    - schedules
#  variables:
#    MACHINE: atlas-board
#  script:
#    - ./bootstrap-yocto
#    - source setup-environment build-atlas
#    - bitbake sd-image
#  tags:
#    - docker
