#!/bin/sh

path="/mnt/nfs"

global bootm.image="${path}/linuximage"

oftree="${path}/socfpga_cyclone5_cp52.dtb"
if [ -f "${oftree}" ]; then
        global bootm.oftree="$oftree"
fi

cp /mnt/nfs/nfsroot/lib/firmware/fpgaimage.rbf /

if [ -e /fpgaimage.rbf ] ; then
	firmwareload /fpgaimage.rbf
	rm /fpgaimage.rbf
	/env/bin/enable_bridges
fi

nfsroot="$eth0.serverip:/tftpboot/$global.user/nfsroot"
ip_route_get -b ${global.net.server} global.linux.bootargs.dyn.ip

global linux.bootargs.dyn.root="root=/dev/nfs nfsroot=${nfsroot},vers=3,tcp,timeo=50 rw"
