#!/bin/sh
if [ -z $nv.user ]; then
	echo "please set user (tftp dir) in settings"
	exit
fi
readf /dev/eeprom0.bootsrc bootsrc
if [ $bootsrc -eq '0' ]; then
	boot=0
else
	boot=1
fi
update_nandroot $nv.user $boot
